trunk-version = "^0.21.1"

[build]
target = "index.html"       # The index HTML file to drive the bundling process.
html_output = "index.html"  # The name of the output HTML file.
dist = "dist"               # The output dir for all final assets.
public_url = "/"            # The public URL from which assets are to be served.

[watch]
# watch = []  # Paths to watch. The `build.target`'s parent folder is watched by default.
# ignore = [] # Paths to ignore.

[serve]
addresses = ["127.0.0.1"]  # The address to serve on.
port = 8080                # The port to serve on.
open = false               # Open a browser tab once the initial build is complete.

[clean]
dist = "dist" # The output dir for all final assets.